### ISSUE TITLE
Failed to run env_test.py 

### ISSUE THREAD

**Issue by phidiaLam** [LamWS/COMP7508_Data_Driven_Animation#2]
Probably on this line, the import needs to be modified to `from viewer import SimpleViewer`, otherwise the `viewer.py` file can't be found properly because of the nested folders.
https://github.com/LamWS/COMP7508_Data_Driven_Animation/blob/b57fd1026d8df00f408d82cb9bf317be5c855ce5/assignment_2/env_test.py#L1

**Comment by Shimingyi** [comment]
Sorry for that, it should:
`from Viewer.viewer import SimpleViewer`

I will update it then
